sentences = [
    "The clock on the wall chimed three times, though it was clearly noon.",
    "A stray feather drifted through the open window and landed on the keyboard.",
    "She bought a yellow umbrella just in case the sky decided to change its mind.",
    "The old oak tree had seen three centuries of quiet morning frost.",
    "He systematically sorted his collection of ocean pebbles by smooth texture.",
    "A gentle breeze carried the distinct scent of fresh roasted coffee beans.",
    "The train whistled softly as it rounded the bend into the valley.",
    "Nobody noticed the cat sleeping peacefully on top of the warm refrigerator.",
    "She unlocked the heavy wooden door to reveal a room full of antique clocks.",
    "The lighthouse light swept rhythmically across the dark, churning waves.",
    "He lost his favorite fountain pen somewhere between the library and the cafe.",
    "A sudden flash of lightning illuminated the empty cobblestone street.",
    "The baker added an extra pinch of cinnamon to the morning pastry dough.",
    "An abandoned bicycle leaned against the rusting iron fence.",
    "She listened closely to the soft patter of rain against the glass.",
    "The paper airplane glided gracefully across the entire length of the room.",
    "He adjusted his glasses before peering down into the deep canyon.",
    "A quiet rustle in the bushes made the squirrel freeze instantly in place.",
    "The library smelled deliciously of old paper, leather bindings, and dust.",
    "She painted the kitchen cabinets a soft shade of sage green.",
    "The compass needle spun wildly before settling point toward the north.",
    "He spent his entire Sunday trying to finish a five-thousand-piece puzzle.",
    "Fresh snow carpeted the silent pine forest in a thick white layer.",
    "A bright red balloon floated away toward the cloudless afternoon sky.",
    "The barista carefully drew a heart in the foam of the hot latte.",
    "She found a forgotten twenty-dollar bill tucked inside a winter coat pocket.",
    "The old radio static suddenly cleared to reveal a faint jazz tune.",
    "He left his boots near the front door to dry after the long trek.",
    "A pod of dolphins broke the surface of the calm ocean water at dawn.",
    "The bookstore owner always recommended strange and obscure poetry books.",
    "Sunlight filtered softly through the thick canopy of ancient cedar trees.",
    "She practiced the violin piece until her fingertips were completely numb.",
    "The streetlamp flickered twice before shutting off completely for the night.",
    "He accidentally poured orange juice into his bowl of morning cereal.",
    "A tiny green sprout pushed its way through a crack in the concrete pavement.",
    "The wooden floorboards creaked under the weight of his gentle footsteps.",
    "She wrapped her hands around the warm ceramic mug of tea.",
    "An owls hoot echoed far off in the darkness of the surrounding woods.",
    "The ancient maps in the archive showed islands that no longer existed.",
    "He folded the letter carefully before sliding it inside the crisp envelope.",
    "A swarm of fireflies illuminated the edge of the meadow at twilight.",
    "She left early to avoid the heavy rush hour traffic on the bridge.",
    "The grandfather clock ticked with a heavy, deliberate rhythm.",
    "He always read the last page of a novel before starting chapter one.",
    "A crisp breeze rustled the fallen orange leaves along the driveway.",
    "The mirror hung slightly crooked against the freshly painted plaster wall.",
    "She pressed a colorful wildflowers between the heavy pages of her journal.",
    "The city skyline sparkled beneath a clear blanket of midnight stars.",
    "He placed the final stone on top of the precarious rock cairn.",
    "The morning fog slowly lifted to reveal the quiet harbor below."
]